### ISSUE TITLE
run_issue miss 

### ISSUE THREAD

**Issue by hquzhuguofeng** [AtmaHou/FewShotMultiLabel#1]
做MLC的任务时候，缺失 tag_data.dict.all
`    def load_tag_data_dict(self):
        tag_data_dir = os.path.dirname(os.path.dirname(self.opt.train_path))
        tag_data_path = os.path.join(tag_data_dir, 'tag_data.dict.all')
        with open(tag_data_path, 'r') as fr:
            tag_data_dict = json.load(fr)
        return tag_data_dict
`

**Comment by laiyongkui1997** [comment]
抱歉，这个数据上传的时候漏掉了。我们会尽快更新。
此外，我们也会将生成该文件的脚本上传供您参考。

**Comment by AtmaHou** [comment]
Thanks for the issue and promote reply.
The problem already fixed~
