### ISSUE TITLE
Different batch_ Size problem

### ISSUE THREAD

**Issue by luoshunchong** [AtmaHou/FewShotMultiLabel#10]
Thank you for opening up such great working code. I can run the file "run_b_stanford_1_main.sh" directly and get the results in your paper. But I found it a little slow. So I modify the set "train_ batch_ size_ LST" to 8 in this file, but the result drops a lot. I don't know why. I hope you can help me.
Thank you very much!
![image](https://user-images.githubusercontent.com/60057336/144741947-129efbfe-eb1c-4b82-b28f-68e482f4c8a4.png)

**Comment by AtmaHou** [comment]
what are the scores？

**Comment by luoshunchong** [comment]
> what are the scores？

the scores
![image](https://user-images.githubusercontent.com/60057336/144753927-5dab9810-95c7-4376-ad3f-09418ba42370.png)
When the "train_ batch_  size_lst" is 4, the result is similar to that in your paper, but when using 8, you can only get 0.3686.I don't know what's wrong with me.Could you help me?

**Comment by AtmaHou** [comment]
> 

We check the old experient logs and do not find a similar problem... 
:(
Seems your model is not fully trained, you can output and show the loss curve of two settings to get more inspects of what happens.
