### ISSUE TITLE
相似分数计算维度对应不上

### ISSUE THREAD

**Issue by Dreamlikec** [AtmaHou/FewShotMultiLabel#11]
![image](https://user-images.githubusercontent.com/18510686/151647558-46fbaf19-4301-4f6b-8482-19b46fd6219c.png)
test_reps的长度是1，但是test_mask却是[1,1], 导致相似度矩阵view的时候发生维度的错误，不知道怎么解决

**Comment by AtmaHou** [comment]
可能是你用的transformer包或者pytorch太新没匹配上导致的，可以试着回退一下版本
不过我没太懂你的问题。。 只有一个test reps，mask按理说就是应该是【batch=1，len=1】吧？
