### ISSUE TITLE
torchnlp

### ISSUE THREAD

**Issue by wws0815** [AtmaHou/FewShotMultiLabel#5]
Hello, I want to ask a question, which is provided by you request.txt Torch > = 1.5.0 is required in. The library torch NLP is used. When I install this library, torch will be automatically updated to 1.0.0. I don't know how to solve this problem? How do you operate it? thank you

**Comment by AtmaHou** [comment]
The torchnlp is inherited from the original platform MetaDialogue and is currently useless.
So I suggest you to try two solutions:
(1) Install torchnlp first and then install PyTorch with a higher version.
(2) Delete all code related to torchnlp.
