### ISSUE TITLE
您好，请问toursg数据集能给份完整的么？谢谢～

### ISSUE THREAD

**Issue by Upper9527** [AtmaHou/FewShotMultiLabel#7]

**Comment by AtmaHou** [comment]
实验需要用的全部数据我已经放在相应位置了，但是全集这个是付费数据，我没有权限提供的~

**Comment by Upper9527** [comment]
只给测试集的15个对话可以么？完整的数据集太贵了，6000多，买不起

**Comment by AtmaHou** [comment]
> 只给测试集的15个对话可以么？完整的数据集太贵了，6000多，买不起

2333，你理解错了，不是因为付费不给你，我们不是数据版权方，没有权限给你。。

**Comment by milan150278** [comment]
请问这个TourSG数据集是不是缺少了tag_data.dict.all这个文件呀？

**Comment by AtmaHou** [comment]
这是哪用到的来着？我看看

**Comment by milan150278** [comment]
> 这是哪用到的来着？我看看

![image](https://user-images.githubusercontent.com/48815474/159826758-07a916ed-0082-4031-827a-c82fefb31784.png)
这里需要加载，是不是我少做了什么操作呀

**Comment by milan150278** [comment]
刚刚看到gen_meta_data.sh这个脚本里好像是处理toursg数据集的，但是又没有config.json哈哈哈，我有点蒙了...昨晚想看下数据集处理工具里写到的几个其他数据集（atis、snips）能不能跑，也是缺这个config文件.... 求指教

**Comment by AtmaHou** [comment]
感谢你的提醒，那个辅助文件也已经update到zip里了~

**Comment by milan150278** [comment]
> 感谢你的提醒，那个辅助文件也已经update到zip里了~

嘻嘻谢谢解答！！另外还想问一下这里列出来的剩下三个数据集中去代码里提供的github地址下载了，但是缺config.json文件，这个是需要自己构造嘛？
![image](https://user-images.githubusercontent.com/48815474/159828852-b11f8e8e-3785-4185-9719-1cb325a5811f.png)

**Comment by AtmaHou** [comment]
应该不用，data里提供的已经是构造好的了

**Comment by milan150278** [comment]
好的，那我再调试一下看看，多谢啦~
