### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by zhangkaifang** [AtmaHou/FewShotMultiLabel#8]
![image](https://user-images.githubusercontent.com/29163376/137862670-d5857da9-c8ef-4f8e-8845-faeb85a045aa.png)

**Comment by michael-wzhu** [comment]
change the code around line 88 to:

for batch_id, batch in enumerate(domain[0]):

**Comment by zhangkaifang** [comment]
Thank you author, can this support the data set construction of Chinese corpus?

**Comment by AtmaHou** [comment]
Thanks @michael-wzhu for the answer!

For Chinese corpus, you need to change the encoder  (1) use Chinese pretrained LM model (2) use Chinese feature extracting tool for label num estimation, such as POS.

**Comment by zhangkaifang** [comment]
Thank you author, can you send me the original DEFAULT_INPUT_PATH ='D:/Data/Project/Data/stanford/' data, or simply give me a few? I want to study the construction process of few shot data, and then modify it into Chinese.

**Comment by zhangkaifang** [comment]
作者这个原始数据stanford可以给一下吗？感谢！
![image](https://user-images.githubusercontent.com/29163376/138073752-d1d9b0e0-c982-432c-8868-07d6bc1bbeea.png)

**Comment by AtmaHou** [comment]
The original data can be downloaded at the readme page:
https://github.com/AtmaHou/FewShotMultiLabel/tree/master/data

For few-shot data construction, we provided a tool for such task:
https://github.com/AtmaHou/MetaDialog#few-shot-data-construction-tool

**Comment by zhangkaifang** [comment]
Thank you very much!

**Comment by zhangkaifang** [comment]
大神您好，可以加一下您的微信吗？

**Comment by AtmaHou** [comment]
可以啊huan迎交流，邮件发我一下id哇~~

**Comment by zhangkaifang** [comment]
谢谢啦，发你邮箱啦。
